// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujohokageagbkbzkpuku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqb2hva2FnZWFnYmtiemtwdWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwOTY0MzMsImV4cCI6MjA1NDY3MjQzM30.RZBGFFlFSAp-wFFcUa9HSzhlNjurzKrsWRY7zffa1ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);